// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from example.djinni

#import "Hien+Private.h"
#import <Djinni/DJIMarshal+Json.h>
#import <Djinni/DJIMarshal+Private.h>
#include <cassert>

namespace djinni_generated {

auto HienHelper::toCpp(ObjcType obj) -> CppType
{
    assert(obj);
    return {::djinni::I8::toCpp(obj.__djinni__objc_val)};
}

auto HienHelper::fromCpp(const CppType& cpp) -> ObjcType
{
    return [Hien initWithVal:(::djinni::I8::fromCpp(cpp.val))];
}

}  // namespace djinni_generated
