// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from example.djinni

#import <DjinniExample/DjinniExample-Swift.h>
#include "hien.hpp"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class Hien;

namespace djinni_generated {

struct HienHelper
{
    using CppType = ::cpp_generated::Hien;
    using ObjcType = Hien*;

    using Boxed = HienHelper;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

}  // namespace djinni_generated
