// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from example.djinni

#pragma once

#include "djinni_support.hpp"
#include "hien.hpp"

namespace djinni_generated {

class NativeHien final {
public:
    using CppType = ::cpp_generated::Hien;
    using JniType = jobject;

    using Boxed = NativeHien;

    ~NativeHien();

    static CppType toCpp(JNIEnv* jniEnv, JniType j);
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c);

private:
    NativeHien();
    friend ::djinni::JniClass<NativeHien>;

    const ::djinni::GlobalRef<jclass> clazz { ::djinni::jniFindClass("demo/auto/gen/Hien") };
    const jmethodID jconstructor { ::djinni::jniGetMethodID(clazz.get(), "<init>", "(B)V") };
    const jfieldID field_mVal { ::djinni::jniGetFieldID(clazz.get(), "mVal", "B") };
};

}  // namespace djinni_generated
