// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from example.djinni

package demo.auto.gen;

import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import java.util.concurrent.atomic.AtomicBoolean;

public abstract class Hello {
    public abstract void print(@NonNull Rc r);

    @NonNull
    public static Hello create()
    {
        return CppProxy.create();
    }

    @NonNull
    public static Hello createWithRc(@NonNull Rc r)
    {
        return CppProxy.createWithRc(r);
    }

    private static final class CppProxy extends Hello
    {
        private final long nativeRef;
        private final AtomicBoolean destroyed = new AtomicBoolean(false);

        private CppProxy(long nativeRef)
        {
            if (nativeRef == 0) throw new RuntimeException("nativeRef is zero");
            this.nativeRef = nativeRef;
        }

        private native void nativeDestroy(long nativeRef);
        public void _djinni_private_destroy()
        {
            boolean destroyed = this.destroyed.getAndSet(true);
            if (!destroyed) nativeDestroy(this.nativeRef);
        }
        protected void finalize() throws java.lang.Throwable
        {
            _djinni_private_destroy();
            super.finalize();
        }

        @Override
        public void print(Rc r)
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            native_print(this.nativeRef, r);
        }
        private native void native_print(long _nativeRef, Rc r);

        @NonNull
        public static native Hello create();

        @NonNull
        public static native Hello createWithRc(@NonNull Rc r);
    }
}
