// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from example.djinni

package demo.auto.gen;

import androidx.annotation.NonNull;
import androidx.annotation.Nullable;

public class Hien {


    /*package*/ final byte mVal;

    public Hien(
            byte val) {
        this.mVal = val;
    }

    public byte getVal() {
        return mVal;
    }

    @Override
    public String toString() {
        return "Hien{" +
                "mVal=" + mVal +
        "}";
    }

}
