// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from example.djinni

package demo.auto.gen;

import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import java.util.ArrayList;

public class Rc {


    /*package*/ final int mA;

    /*package*/ final int mB;

    /*package*/ final long mC;

    /*package*/ final String mD;

    /*package*/ final ArrayList<Short> mList16;

    /*package*/ final ArrayList<Integer> mList;

    /*package*/ final ArrayList<Byte> mList8;

    /*package*/ final ArrayList<Hien> mListHien;

    public Rc(
            int a,
            int b,
            long c,
            @NonNull String d,
            @NonNull ArrayList<Short> list16,
            @NonNull ArrayList<Integer> list,
            @NonNull ArrayList<Byte> list8,
            @NonNull ArrayList<Hien> listHien) {
        this.mA = a;
        this.mB = b;
        this.mC = c;
        this.mD = d;
        this.mList16 = list16;
        this.mList = list;
        this.mList8 = list8;
        this.mListHien = listHien;
    }

    public int getA() {
        return mA;
    }

    public int getB() {
        return mB;
    }

    public long getC() {
        return mC;
    }

    @NonNull
    public String getD() {
        return mD;
    }

    @NonNull
    public ArrayList<Short> getList16() {
        return mList16;
    }

    @NonNull
    public ArrayList<Integer> getList() {
        return mList;
    }

    @NonNull
    public ArrayList<Byte> getList8() {
        return mList8;
    }

    @NonNull
    public ArrayList<Hien> getListHien() {
        return mListHien;
    }

    @Override
    public String toString() {
        return "Rc{" +
                "mA=" + mA +
                "," + "mB=" + mB +
                "," + "mC=" + mC +
                "," + "mD=" + mD +
                "," + "mList16=" + mList16 +
                "," + "mList=" + mList +
                "," + "mList8=" + mList8 +
                "," + "mListHien=" + mListHien +
        "}";
    }

}
