// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from example.djinni

#pragma once

#include <cstdint>
#include <string>
#include <utility>

namespace cpp_generated {

struct  Hien {
    int8_t val;

    Hien(int8_t val_)
    : val(std::move(val_))
    {}

    Hien() = default;
};

}  // namespace cpp_generated
