// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from example.djinni

#include "hien.hpp"  // my header
#include <sstream>

namespace cpp_generated {


}  // namespace cpp_generated
