// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from example.djinni

#include "hien.hpp"  // my header
#include "hien+json.hpp"
#include <sstream>

namespace textsort {

nlohmann::json Hien::to_json() const {
    return ((nlohmann::json)(*this));
}

}  // namespace textsort
