// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from example.djinni

#include "rc.hpp"  // my header
#include <sstream>

namespace textsort {

std::string Rc::description() const {
    return ((nlohmann::json)(*this)).dump(2);
}

}  // namespace textsort
