// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from example.djinni

#pragma once

#include "hien.hpp"
#include <cstdint>
#include <string>
#include <utility>
#include <vector>

namespace cpp_generated {

struct  Rc {
    int32_t a;
    int32_t b;
    uint32_t c;
    std::string d;
    std::vector<int16_t> list_16;
    std::vector<int32_t> list;
    std::vector<int8_t> list8;
    std::vector<Hien> list_hien;

    Rc(int32_t a_,
       int32_t b_,
       uint32_t c_,
       std::string d_,
       std::vector<int16_t> list_16_,
       std::vector<int32_t> list_,
       std::vector<int8_t> list8_,
       std::vector<Hien> list_hien_)
    : a(std::move(a_))
    , b(std::move(b_))
    , c(std::move(c_))
    , d(std::move(d_))
    , list_16(std::move(list_16_))
    , list(std::move(list_))
    , list8(std::move(list8_))
    , list_hien(std::move(list_hien_))
    {}

    Rc() = default;
};

}  // namespace cpp_generated
