// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from example.djinni

#pragma once

#include "cgo_wrapper_marshal.h"

#include "cgo__hien.h"
#include "hien.hpp"
#include <optional>
#include <stdint.h>

struct DjinniCgoHien
{
    static cgo__hien from_cpp(const ::textsort::Hien & cpp);
    static ::textsort::Hien to_cpp(const cgo__hien & cgo);
    static std::shared_ptr<cgo__hien> from_cpp(const std::optional<::textsort::Hien> & cpp);
    static std::optional<::textsort::Hien> to_cpp(cgo__hien * cgo);
};
