// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from example.djinni

#pragma once

#include "cgo_wrapper_marshal.h"

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef struct cgo__hien_ {
    int8_t val;
} cgo__hien;

void cgo__hien__delete(cgo__hien *);
#define cgo__hien__init {}

#ifdef __cplusplus
}
#endif
