// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from 

#include "cgo_wrapper_marshal.hpp"

#include "cgo__hien.hpp"

void cgo__hien__delete(cgo__hien * ptr)
{
};

cgo__hien DjinniCgoHien::from_cpp(const ::textsort::Hien & cpp)
{
    return 
    {
        std::move(cpp.val)};
};

::textsort::Hien DjinniCgoHien::to_cpp(const cgo__hien & cgo)
{
    return 
    {
        std::move(cgo.val)};
};

std::shared_ptr<cgo__hien> DjinniCgoHien::from_cpp(const std::optional<::textsort::Hien> & cpp)
{
    if (cpp.has_value())
    {
        return std::make_shared<cgo__hien>(from_cpp(std::move(*cpp)));
    }
    return std::nullptr;
};

std::optional<::textsort::Hien> DjinniCgoHien::to_cpp(cgo__hien * cgo)
{
    if (cgo != NULL)
    {
        return DjinniCgoHien::to_cpp(cgo);
    }
    return std::nullopt;
};
