// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from 

#include "cgo_wrapper_marshal.hpp"

#include "cgo__hello.h"
#include "cgo__hello.hpp"
#include "cgo__rc.hpp"
#include "hello.hpp"
#include "rc.hpp"

cgo__hello * create(void)
{
    auto ptr = ::cpp_generated::Hello::create();
    return reinterpret_cast<cgo__hello *>(ptr.get());};


cgo__hello * create_with_rc(cgo__rc r)
{
    auto ptr = ::cpp_generated::Hello::create_with_rc(DjinniCgoRc::to_cpp(r));
    return reinterpret_cast<cgo__hello *>(ptr.get());};


void print(cgo__hello * cgo_this, cgo__rc r)
{
    ::cpp_generated::Hello * ptr = reinterpret_cast<::cpp_generated::Hello*>(cgo_this);
    ptr->print(DjinniCgoRc::to_cpp(r));
};

