// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from example.djinni

#pragma once

#include "cgo_wrapper_marshal.h"

#include "cgo__hien.h"
#include "hien.hpp"
#include <stdint.h>

struct DjinniCgoHien
{
    static cgo__hien from_cpp(const ::cpp_generated::Hien & cpp);
    static ::cpp_generated::Hien to_cpp(const cgo__hien & cgo);
};
