// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from example.djinni

#pragma once

#include "cgo_wrapper_marshal.h"

#include "cgo__hien.h"
#include "cgo__hien.hpp"
#include "cgo__list__cgo__hien.h"
#include "cgo__list__cgo__hien.hpp"
#include "cgo__list__int16_t.h"
#include "cgo__list__int16_t.hpp"
#include "cgo__list__int32_t.h"
#include "cgo__list__int32_t.hpp"
#include "cgo__list__int8_t.h"
#include "cgo__list__int8_t.hpp"
#include "hien.hpp"
#include <stdint.h>
#include <string>


struct DjinniCgoListInt32T
{
    static cgo__list__int32_t from_cpp(const std::vector<int32_t> & data);
    static std::vector<int32_t> to_cpp(const cgo__list__int32_t & data);
};
