// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from 

#include "cgo_wrapper_marshal.hpp"

#include "cgo__hien.hpp"

cgo__hien DjinniCgoHien::from_cpp(const ::cpp_generated::Hien & cpp)
{
    return 
    {
        std::move(cpp.val)};
};

::cpp_generated::Hien DjinniCgoHien::to_cpp(const cgo__hien & cgo)
{
    return 
    {
        std::move(cgo.val)};
};
