// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from 

#include "cgo_wrapper_marshal.hpp"

#include "cgo__hien.hpp"
#include "cgo__list__cgo__hien.hpp"
#include "cgo__list__int16_t.hpp"
#include "cgo__list__int32_t.hpp"
#include "cgo__list__int8_t.hpp"
#include "hien.hpp"
#include <stdint.h>
#include <string>

cgo__list__int16_t DjinniCgoListInt16T::from_cpp(const std::vector<int16_t> & data)
{
    cgo__list__int16_t cgo;
    cgo.length = data.size();
    cgo.data = new int16_t[cgo.length];
    for (int i = 0; i < cgo.length; i++)
    {
        cgo.data[i] = std::move(data[i]);
    };
    return cgo;
};

std::vector<int16_t> DjinniCgoListInt16T::to_cpp(const cgo__list__int16_t & cgo)
{
    return std::vector<int16_t>(cgo.data, cgo.data + cgo.length);
};
