// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from example.djinni

#pragma once

#include "cgo_wrapper_marshal.h"

#include "cgo__en.h"
#include "cgo__hien.h"
#include "cgo__list__cgo__hien.h"
#include "cgo__list__int16_t.h"
#include "cgo__list__int32_t.h"
#include "cgo__list__int8_t.h"
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef struct {
    int32_t a;
    int32_t b;
    uint32_t c;
    cgo__string d;
    cgo__list__int16_t list_16;
    cgo__list__int32_t list;
    cgo__list__int8_t list8;
    cgo__list__cgo__hien list_hien;
    uint16_t * o;
    cgo__hien * o1;
    cgo__en e1;
    cgo__en * e2;
}
cgo__rc;

#ifdef __cplusplus
}
#endif
