// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from example.djinni

#pragma once

#include "cgo_wrapper_marshal.h"

#include "cgo__en.h"
#include "cgo__hien.h"
#include "cgo__list__cgo__hien.h"
#include "cgo__list__int16_t.h"
#include "cgo__list__int32_t.h"
#include "cgo__list__int8_t.h"
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef struct {
    size_t length;
    int8_t * data;
}
cgo__list__int8_t;

#ifdef __cplusplus
}
#endif
