// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from 

#include "cgo_wrapper_marshal.hpp"

#include "cgo__rc.hpp"

cgo__rc DjinniCgoRc::from_cpp(const ::cpp_generated::Rc & cpp)
{
    return 
    {
        std::move(cpp.a),
        std::move(cpp.b),
        std::move(cpp.c),
        DjinniString::from_cpp(std::move(cpp.d)),
        DjinniCgoListInt16T::from_cpp(std::move(cpp.list_16)),
        DjinniCgoListInt32T::from_cpp(std::move(cpp.list)),
        DjinniCgoListInt8T::from_cpp(std::move(cpp.list8)),
        DjinniCgoListCgoHien::from_cpp(std::move(cpp.list_hien))};
};

::cpp_generated::Rc DjinniCgoRc::to_cpp(const cgo__rc & cgo)
{
    return 
    {
        std::move(cgo.a),
        std::move(cgo.b),
        std::move(cgo.c),
        DjinniString::to_cpp(std::move(cgo.d)),
        DjinniCgoListInt16T::to_cpp(std::move(cgo.list_16)),
        DjinniCgoListInt32T::to_cpp(std::move(cgo.list)),
        DjinniCgoListInt8T::to_cpp(std::move(cgo.list8)),
        DjinniCgoListCgoHien::to_cpp(std::move(cgo.list_hien))};
};
