// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from example.djinni

#pragma once

#include "cgo_wrapper_marshal.h"

#include "cgo__en.h"
#include "cgo__en.hpp"
#include "cgo__hien.h"
#include "cgo__hien.hpp"
#include "cgo__list__cgo__hien.h"
#include "cgo__list__cgo__hien.hpp"
#include "cgo__list__int16_t.h"
#include "cgo__list__int16_t.hpp"
#include "cgo__list__int32_t.h"
#include "cgo__list__int32_t.hpp"
#include "cgo__list__int8_t.h"
#include "cgo__list__int8_t.hpp"
#include "en.hpp"
#include "hien.hpp"
#include <optional>
#include <stdint.h>
#include <string>


struct DjinniCgoListCgoHien
{
    static cgo__list__cgo__hien from_cpp(const std::vector<::cpp_generated::Hien> & data);
    static std::vector<::cpp_generated::Hien> to_cpp(const cgo__list__cgo__hien & data);
};
