// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from 

#include "cgo_wrapper_marshal.hpp"

#include "cgo__en.hpp"
#include "cgo__hien.hpp"
#include "cgo__list__cgo__hien.hpp"
#include "cgo__list__int16_t.hpp"
#include "cgo__list__int32_t.hpp"
#include "cgo__list__int8_t.hpp"
#include "en.hpp"
#include "hien.hpp"
#include <optional>
#include <stdint.h>
#include <string>

cgo__list__cgo__hien DjinniCgoListCgoHien::from_cpp(const std::vector<::cpp_generated::Hien> & data)
{
    cgo__list__cgo__hien cgo;
    cgo.length = data.size();
    cgo.data = new cgo__hien[cgo.length];
    for (int i = 0; i < cgo.length; i++)
    {
        cgo.data[i] = DjinniCgoHien::from_cpp(data[i]);
    };
    return cgo;
};

std::vector<::cpp_generated::Hien> DjinniCgoListCgoHien::to_cpp(const cgo__list__cgo__hien & cgo)
{
    std::vector<::cpp_generated::Hien> cpp = std::vector<::cpp_generated::Hien>(cgo.length);
    for (int i = 0; i < cpp.size(); i++)
    {
        cpp[i] = DjinniCgoHien::to_cpp(cgo.data[i]);
    }
    return cpp;
};
