fastlane_version "2.70.1"
default_platform :ios

def get_libary_version
    return '4.7.0'
end

lane :submit_podspecs do
    version_bump_podspec(path: "Djinni.podspec", version_number: get_libary_version)

    pod_push(path: "Djinni.podspec",
        repo: "misfit-podspecs",
        allow_warnings: true,
        skip_import_validation: true,
        use_libraries: true,
        verbose: true)

    version_bump_podspec(path: "DjinniSwift.podspec", version_number: get_libary_version)
    pod_push(path: "DjinniSwift.podspec",
        repo: "misfit-podspecs",
        sources: ['git@bitbucket.org:misfitwearablesinc/misfit-podspecs.git','https://github.com/CocoaPods/Specs.git'],
        allow_warnings: true,
        verbose: true,
        skip_import_validation: true,
        use_libraries: true)

end