// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from example.djinni

package com.dropbox.textsort;

import java.util.ArrayList;
import javax.annotation.CheckForNull;
import javax.annotation.Nonnull;

/*package*/ class Rc {


    /*package*/ final int mA;

    /*package*/ final int mB;

    /*package*/ final long mC;

    /*package*/ final String mD;

    /*package*/ final ArrayList<Integer> mList;

    public Rc(
            int a,
            int b,
            long c,
            @Nonnull String d,
            @Nonnull ArrayList<Integer> list) {
        this.mA = a;
        this.mB = b;
        this.mC = c;
        this.mD = d;
        this.mList = list;
    }

    public int getA() {
        return mA;
    }

    public int getB() {
        return mB;
    }

    public long getC() {
        return mC;
    }

    @Nonnull
    public String getD() {
        return mD;
    }

    @Nonnull
    public ArrayList<Integer> getList() {
        return mList;
    }

    @Override
    public String toString() {
        return "Rc{" +
                "mA=" + mA +
                "," + "mB=" + mB +
                "," + "mC=" + mC +
                "," + "mD=" + mD +
                "," + "mList=" + mList +
        "}";
    }

}
