// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from example.djinni

import DjinniSwift
import Foundation

extension Hien  {
    @available(swift, obsoleted: 1.0)
    @objc public var __djinni__objc_val: Int8 {
        get {
            return val
        }
    }
    @available(swift, obsoleted: 1.0)
    @objc public static func `init`(val: Int8) -> Hien {
        return Hien.init(val: val)}
}
