// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from example.djinni

import DjinniSwift
import Foundation

@objc public class Hien : NSObject {

    public let val : Int8

    public init(val: Int8) {
        self.val = val
    }
}
