// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from example.djinni

import DjinniSwift
import Foundation

@objc public class Rc : NSObject {

    public let a : Int32

    public let b : Int32

    public let c : UInt32

    public let d : String

    public let list16 : Array<Int16>

    public let list : Array<Int32>

    public let list8 : Array<Int8>

    public let listHien : Array<Hien>

    public let o : UInt16?

    public let o1 : Hien?

    public let e1 : En

    public let e2 : En?

    public init(a: Int32,
                b: Int32,
                c: UInt32,
                d: String,
                list16: Array<Int16>,
                list: Array<Int32>,
                list8: Array<Int8>,
                listHien: Array<Hien>,
                o: UInt16?,
                o1: Hien?,
                e1: En,
                e2: En?) {
        self.a = a
        self.b = b
        self.c = c
        self.d = d
        self.list16 = list16
        self.list = list
        self.list8 = list8
        self.listHien = listHien
        self.o = o
        self.o1 = o1
        self.e1 = e1
        self.e2 = e2
    }
}
